# Generated by Django 6.0 on 2025-12-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['titulo'], 'verbose_name_plural': 'Galerías'},
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='iframe',
        ),
        migrations.AddField(
            model_name='galeria',
            name='url',
            field=models.URLField(default='', help_text='Enlace público de Google Fotos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galeria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='titulo',
            field=models.CharField(max_length=120, verbose_name='Nombre del álbum'),
        ),
    ]
