# Generated by Django 6.0 on 2025-12-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_galeria_options_remove_galeria_iframe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(max_length=300)),
                ('memoria', models.TextField()),
                ('foto', models.ImageField(upload_to='pub_fotos/')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
