# Generated by Django 6.0 on 2025-12-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='galeria/', verbose_name='Imagen de portada'),
        ),
    ]
