# Generated by Django 5.2.9 on 2025-12-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_galeria_descripcion_galeria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='album_url',
            field=models.URLField(blank=True, verbose_name='Enlace a álbum Google Photos'),
        ),
    ]
